build fix: empty meta file no longer allowed
there's a bug somewhere that crashes with:

aosp-chicken-install -s -keep-installed
retrieving ...
checking platform for `cube-server' ...
checking dependencies for `cube-server' ...

Error: (assq) bad argument type: #!eof
Makefile:13: recipe for target 'modules' failed

when a meta file is empty.