dab fix: compile warning
~/adellica/projects/cube/aosp/external/cube-server/dab $ chicken-install -n
retrieving ...
checking platform for `dab' ...
checking dependencies for `dab' ...
install order:
("dab")
installing dab: ...
changing current directory to .
  '/usr/local/bin/csi' -bnq -setup-mode -e "(require-library setup-api)" -e "(import setup-api)" -e "(setup-error-handling)" -e "(extension-name-and-version '(\"dab\" \"\"))" -e "(keep-intermediates #t)" -e "(setup-install-mode #f)" 'dab.setup'
  '/usr/local/bin/csc' -feature compiling-extension -setup-mode -k   -dynamic -optimize-level 3 -debug-level 1 dab.scm -emit-import-library dab

Warning: reference to possibly unbound identifier `filter' in:
Warning:    dab-channels*
Warning:    suggesting: `(import srfi-1)'

Error: module unresolved: dab

Error: shell command terminated with non-zero exit status 256: '/usr/local/bin/chicken' 'dab.scm' -output-file 'dab.c' -dynamic -feature chicken-compile-shared -feature compiling-extension -setup-mode -optimize-level 3 -debug-level 1 -emit-import-library dab

Error: shell command failed with nonzero exit status 256:

  '/usr/local/bin/csc' -feature compiling-extension -setup-mode -k   -dynamic -optimize-level 3 -debug-level 1 dab.scm -emit-import-library dab

Error: shell command terminated with nonzero exit code
17920
"'/usr/local/bin/csi' -bnq -setup-mode -e \"(require-library setup-api)\" -e \"(...